# Generated by Django 5.2 on 2025-04-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_users_firstname_users_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='LastName',
            new_name='network',
        ),
    ]
