# Generated by Django 5.2 on 2025-04-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_lastname_users_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='network',
            new_name='Network',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Age',
            new_name='releasdate',
        ),
    ]
