# Generated by Django 5.2 on 2025-04-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_network_users_network_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='EmailAddress',
            new_name='Disc',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='releasdate',
            new_name='Releasdate',
        ),
    ]
