# Generated by Django 5.2 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_emailaddress_users_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Releasdate',
            field=models.DateField(),
        ),
    ]
