# Generated by Django 5.2 on 2025-04-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_users_releasdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Show',
        ),
    ]
